build: false  # Not a C# project, build stuff at the test step instead.
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python33"
    - PYTHON: "C:/Python34"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/Scripts/pip.exe install tox"

test_script:
  - "%PYTHON%/Scripts/tox.exe"
